import type { ContentCategory, GeneratedContent } from './types';

export const CONTENT_CATEGORIES: ContentCategory[] = [
    {
        id: 'performanceReport',
        title: 'Relatório de Performance',
        items: [
            { id: 'performanceSummary', label: 'Resumo da Performance', accessor: (c: GeneratedContent) => c.performanceReport },
        ],
    },
    {
        id: 'copywritingAndAdvertising',
        title: 'Copywriting e Publicidade',
        items: [
            { id: 'persuasiveDescriptions', label: 'Descrições Persuasivas (8-12)', accessor: (c: GeneratedContent) => c.copywritingAndAdvertising.persuasiveDescriptions },
            { id: 'catchyHeadlines', label: 'Títulos Chamativos (15-20)', accessor: (c: GeneratedContent) => c.copywritingAndAdvertising.catchyHeadlines },
            { id: 'paidAdCopy', label: 'Copy para Anúncios Pagos (com Score)', accessor: (c: GeneratedContent) => c.copywritingAndAdvertising.paidAdCopy },
            { id: 'benefitsVsFeatures', label: 'Benefícios vs. Recursos', accessor: (c: GeneratedContent) => c.copywritingAndAdvertising.benefitsVsFeatures },
            { id: 'ctas', label: 'Call-to-Actions (CTAs) (5-10)', accessor: (c: GeneratedContent) => c.copywritingAndAdvertising.ctas },
            { id: 'promotionalSalePhrases', label: 'Frases Promocionais de Venda (10-15)', accessor: (c: GeneratedContent) => c.copywritingAndAdvertising.promotionalSalePhrases },
            { id: 'slogans', label: 'Slogans Publicitários (10-15)', accessor: (c: GeneratedContent) => c.copywritingAndAdvertising.slogans },
            { id: 'alternativeAdTitles', label: 'Títulos Alternativos para Anúncios', accessor: (c: GeneratedContent) => c.copywritingAndAdvertising.alternativeAdTitles },
            { id: 'remarketingPhrases', label: 'Frases para Remarketing (3-5)', accessor: (c: GeneratedContent) => c.copywritingAndAdvertising.remarketingPhrases },
            { id: 'technicalDescriptions', label: 'Descrições Técnicas Detalhadas (1-2)', accessor: (c: GeneratedContent) => c.copywritingAndAdvertising.technicalDescriptions },
            { id: 'negativeCommentResponses', label: 'Respostas para Comentários Negativos (2-4)', accessor: (c: GeneratedContent) => c.copywritingAndAdvertising.negativeCommentResponses },
            { id: 'thankYouCardMessages', label: 'Mensagens para Cartão de Agradecimento (2-4)', accessor: (c: GeneratedContent) => c.copywritingAndAdvertising.thankYouCardMessages },
            { id: 'productPackagingTexts', label: 'Textos para Embalagem do Produto (2-4)', accessor: (c: GeneratedContent) => c.copywritingAndAdvertising.productPackagingTexts },
        ],
    },
    {
        id: 'salesAndConversion',
        title: 'Vendas e Conversão',
        items: [
            { id: 'marketplacePricing', label: 'Preços para Marketplaces', accessor: (c: GeneratedContent) => c.salesAndConversion.marketplacePricing },
            { id: 'competitorPriceAnalysis', label: 'Análise de Preço da Concorrência', accessor: (c: GeneratedContent) => c.salesAndConversion.competitorPriceAnalysis },
            { id: 'pricePositioning', label: 'Comparação de Preços e Posicionamento', accessor: (c: GeneratedContent) => c.salesAndConversion.pricePositioning },
            { id: 'priceVariations', label: 'Variações de Preço e Descontos (3–5)', accessor: (c: GeneratedContent) => c.salesAndConversion.priceVariations },
            { id: 'competitorComparisons', label: 'Comparativos com Concorrentes (1-3)', accessor: (c: GeneratedContent) => c.salesAndConversion.competitorComparisons },
            { id: 'discountCoupons', label: 'Cupons de Desconto (5–10)', accessor: (c: GeneratedContent) => c.salesAndConversion.discountCoupons },
            { id: 'suggestedCategoriesAndTags', label: 'Sugestão de Categorias e Tags', accessor: (c: GeneratedContent) => c.salesAndConversion.suggestedCategoriesAndTags },
            { id: 'promotionalPopups', label: 'Textos para Pop-ups (3–5)', accessor: (c: GeneratedContent) => c.salesAndConversion.promotionalPopups },
            { id: 'promotionCountdowns', label: 'Contagens Regressivas (1–3)', accessor: (c: GeneratedContent) => c.salesAndConversion.promotionCountdowns },
            { id: 'campaignLandingPages', label: 'Conteúdo para Landing Pages (1-2)', accessor: (c: GeneratedContent) => c.salesAndConversion.campaignLandingPages },
            { id: 'serviceChatbots', label: 'Scripts para Chatbots (1–2)', accessor: (c: GeneratedContent) => c.salesAndConversion.serviceChatbots },
            { id: 'interactiveQuizzes', label: 'Quizzes Interativos (2–3)', accessor: (c: GeneratedContent) => c.salesAndConversion.interactiveQuizzes },
        ],
    },
    {
        id: 'customerFeedback',
        title: 'Análise de Feedback',
        items: [
            { id: 'sentimentAnalysis', label: 'Análise de Sentimento de Avaliações', accessor: (c: GeneratedContent) => c.customerFeedback.sentimentAnalysis },
        ],
    },
    {
        id: 'socialMediaAndEngagement',
        title: 'Redes Sociais e Engajamento',
        items: [
            { id: 'socialMediaPosts', label: 'Frases para Posts (10-15)', accessor: (c: GeneratedContent) => c.socialMediaAndEngagement.socialMediaPosts },
            { id: 'instagramCaptions', label: 'Legendas para Instagram (3-5)', accessor: (c: GeneratedContent) => c.socialMediaAndEngagement.instagramCaptions },
            { id: 'popularHashtags', label: 'Hashtags Populares (50-60)', accessor: (c: GeneratedContent) => c.socialMediaAndEngagement.popularHashtags },
            { id: 'shortVideoScripts', label: 'Scripts para Vídeos Curtos (4-5)', accessor: (c: GeneratedContent) => c.socialMediaAndEngagement.shortVideoScripts },
            { id: 'youtubeVideoDescriptions', label: 'Descrições para Vídeos no YouTube (2-3)', accessor: (c: GeneratedContent) => c.socialMediaAndEngagement.youtubeVideoDescriptions },
            { id: 'storyTexts', label: 'Textos para Stories (Enquetes, Perguntas) (3-5)', accessor: (c: GeneratedContent) => c.socialMediaAndEngagement.storyTexts },
            { id: 'tweets', label: 'Tweets Prontos (3-5)', accessor: (c: GeneratedContent) => c.socialMediaAndEngagement.tweets },
            { id: 'facebookGroupPosts', label: 'Posts para Grupos no Facebook (2-3)', accessor: (c: GeneratedContent) => c.socialMediaAndEngagement.facebookGroupPosts },
            { id: 'viralPhrases', label: 'Frases Virais (5-10)', accessor: (c: GeneratedContent) => c.socialMediaAndEngagement.viralPhrases },
            { id: 'instagramBio', label: 'Bio para Instagram/TikTok (1-3)', accessor: (c: GeneratedContent) => c.socialMediaAndEngagement.instagramBio },
        ],
    },
    {
        id: 'seoAndBlog',
        title: 'SEO e Conteúdo para Blogs',
        items: [
            { id: 'seoTitles', label: 'Títulos SEO (15-20)', accessor: (c: GeneratedContent) => c.seoAndBlog.seoTitles },
            { id: 'metaDescriptions', label: 'Meta Descriptions Otimizadas (3-5)', accessor: (c: GeneratedContent) => c.seoAndBlog.metaDescriptions },
            { id: 'seoTags', label: 'Tags SEO Relevantes (50-60)', accessor: (c: GeneratedContent) => c.seoAndBlog.seoTags },
            { id: 'longTailKeywords', label: 'Keywords Long-Tail (10-15)', accessor: (c: GeneratedContent) => c.seoAndBlog.longTailKeywords },
            { id: 'faq', label: 'Perguntas Frequentes (FAQ) (5-10)', accessor: (c: GeneratedContent) => c.seoAndBlog.faq },
            { id: 'seoBlogPosts', label: 'Artigos para Blog Otimizados (2-3)', accessor: (c: GeneratedContent) => c.seoAndBlog.seoBlogPosts },
            { id: 'blogPostIntroductions', label: 'Introduções para Artigos de Blog (2-4)', accessor: (c: GeneratedContent) => c.seoAndBlog.blogPostIntroductions },
            { id: 'blogPostConclusions', label: 'Conclusões para Artigos com CTA (2-4)', accessor: (c: GeneratedContent) => c.seoAndBlog.blogPostConclusions },
            { id: 'metaTagsAndAltText', label: 'Meta Tags e Alt Text (5-10)', accessor: (c: GeneratedContent) => c.seoAndBlog.metaTagsAndAltText },
        ],
    },
    {
        id: 'emailMarketingAndAutomation',
        title: 'E-mail Marketing e Automação',
        items: [
            { id: 'personalizedMarketingEmails', label: 'E-mails Marketing Personalizados (2-3)', accessor: (c: GeneratedContent) => c.emailMarketingAndAutomation.personalizedMarketingEmails },
            { id: 'abandonedCartEmails', label: 'E-mails de Recuperação de Carrinho (2-3)', accessor: (c: GeneratedContent) => c.emailMarketingAndAutomation.abandonedCartEmails },
            { id: 'welcomeEmails', label: 'E-mail de Boas-Vindas (1-2)', accessor: (c: GeneratedContent) => c.emailMarketingAndAutomation.welcomeEmails },
            { id: 'newsletters', label: 'Newsletters Semanais (1-2)', accessor: (c: GeneratedContent) => c.emailMarketingAndAutomation.newsletters },
            { id: 'leadNurturingSequence', label: 'Sequência de E-mails de Nutrição (1-2)', accessor: (c: GeneratedContent) => c.emailMarketingAndAutomation.leadNurturingSequence },
            { id: 'reactivationEmails', label: 'E-mails de Reativação de Clientes (1-2)', accessor: (c: GeneratedContent) => c.emailMarketingAndAutomation.reactivationEmails },
        ],
    },
    {
        id: 'other',
        title: 'Outros Conteúdos',
        items: [
            { id: 'fakeTestimonials', label: 'Depoimentos Fictícios (4-6)', accessor: (c: GeneratedContent) => c.other.fakeTestimonials },
            { id: 'purchaseGuides', label: 'Guias de Compra Comparativos (2-4)', accessor: (c: GeneratedContent) => c.other.purchaseGuides },
        ],
    },
];